from random import choice
dict_verb = {
    "IR": "TO GO",
    "VENIR": "TO COME",
    "TOMAR": "TO TAKE",
    "DAR": "TO GIVE",
    "MANTENER": "TO KEEP",
    "DEJAR": "TO LET",
    "VER": "TO SEE",
    "DECIR": "TO SAY",
    "PARECER": "TO SEEM",
    "CONSEGUIR": "TO GET",
    "HACER-ACCION": "TO DO",
    "HACER-CREAR": "TO MAKE",
    "PONER": "TO PUT",
    "SER O ESTAR": "TO BE",
    "ENVIAR": "TO SEND",
    "TENER": "TO HAVE"
}

dict_pronombres = {
    "YO" :"I",
    "TU" : "YOU",
    "NOSOTROS" : "WE",
    "ELLA" : "SHE",
    "EL" : "HE",
    "ESO" : "IT",
    "ELLOS" : "THEY",
    "USTEDES" : "YOU",
    
}

frase_pronombre_and_verbs = {
    "YO VOY" : "I GO",
    "TU VAS" : "YOU GO",
    "NOSOTROS VAMOS" : "WE GO",
    "EL VA" : "HE GOES",
    "ELLA VA" : "SHE GOES",
    "ESO VA" : "IT GOES",
    "ELLOS VAN" : "THEY GO",
    "USTEDES VAN" : "YOU GO",
    "YO VENGO" : "I COME",
    "TU VIENES" : "YOU COME",
    "NOSOTROS VENIMOS" : "WE COME",
    "EL VIENE" : "HE COMES",
    "ELLA VIENE" : "SHE COMES",
    "ESO VIENE" : "IT COMES",
    "ELLOS VIENEN" : "THEY COME",
    "USTEDES VIENEN" : "YOU COME",
    "YO DOY" : "I GIVE",
    "TU DAS" : "YOU GIVE",
    "NOSOTROS DAMOS" : "WE GIVE",
    "EL DA" : "HE GIVES",
    "ELLA DA" : "SHE GIVES",
    "ESO DA" : "IT GIVES",
    "ELLOS DAN" : "THEY GIVE",
    "USTEDES DAN" : "YOU GIVE",
    "YO TOMO" : "I TAKE",
    "TU TOMAS" : "YOU TAKE",
    "NOSOTROS TOMAMOS" : "WE TAKE",
    "EL TOMA" : "HE TAKES",
    "ELLA TOMA" : "SHE TAKES",
    "ESO TOMA" : "IT TAKES",
    "ELLOS TOMAN" : "THEY TAKE",
    "USTEDES TOMAN" : "YOU TAKE",
    "YO MANTENGO" : "I KEEP",
    "TU MANTIENES" : "YOU KEEP",
    "NOSOTROS MANTENEMOS" : "WE KEEP",
    "EL MANTIENE" : "HE KEEPS",
    "ELLA MANTIENE" : "SHE KEEPS",
    "ESO MANTIENE" : "IT KEEPS",
    "ELLOS MANTIENEN" : "THEY KEEP",
    "USTEDES MANTIENEN" : "YOU KEEP",
    "YO DEJO" : "I LET",
    "TU DEJAS" : "YOU LET",
    "NOSOTROS DEJAMOS" : "WE LET",
    "EL DEJA" : "HE LETS",
    "ELLA DEJA" : "SHE LETS",
    "ESO DEJA" : "IT LETS",
    "ELLOS DEJAN" : "THEY LET",
    "USTEDES DEJAN" : "YOU LET",
    "YO VEO" : "I SEE",
    "TU VES" : "YOU SEE",
    "NOSOTROS VEMOS" : "WE SEE",
    "EL VE" : "HE SEES",
    "ELLA VE" : "SHE SEES",
    "ESO VE" : "IT SEES",
    "ELLOS VEN" : "THEY SEE",
    "USTEDES VEN" : "YOU SEE",
    "YO PAREZCO" : "I SEEM",
    "TU PARECES" : "YOU SEEM",
    "NOSOTROS PARECEMOS" : "WE SEEM",
    "EL PARECE" : "HE SEEMS",
    "ELLA PARECE" : "SHE SEEMS",
    "ESO PARECE" : "IT SEEMS",
    "ELLOS PARECEN" : "THEY SEEM",
    "USTEDES PARECEN" : "YOU SEEM",
    "YO CONSIGO" : "I GET",
    "TU CONSIGUES" : "YOU GET",
    "NOSOTROS CONSEGUIMOS" : "WE GET",
    "EL CONSIGUE" : "HE GETS",
    "ELLA CONSIGUE" : "SHE GETS",
    "ESO CONSIGUE" : "IT GETS",
    "ELLOS CONSIGUEN" : "THEY GET",
    "USTEDES CONSIGUEN" : "YOU GET",
    "YO HAGO/ACCION" : "I DO",
    "TU HACES/ACCION" : "YOU DO",
    "NOSOTROS HACEMOS/ACCION" : "WE DO",
    "EL HACE/ACCION" : "HE DOES",
    "ELLA HACE/ACCION" : "SHE DOES",
    "ESO HACE/ACCION" : "IT DOES",
    "ELLOS HACE/ACCION" : "THEY DO",
    "USTEDES HACEN/ACCION" : "YOU DO",
    "YO HAGO/CREAR" : "I MAKE",
    "TU HAGO/CREAR" : "YOU MAKE",
    "NOSOTROS HACEMOS/CREAR" : "WE MAKE",
    "EL HACE/CREAR" : "HE MAKES",
    "ELLA HACE/CREAR" : "SHE MAKES",
    "ESO HACE/CREAR" : "IT MAKES",
    "ELLOS HACEN/CREAR" : "THEY MAKES",
    "USTEDES HACEN/CREAR" : "YOU MAKE",
    "YO PONGO" : "I PUT",
    "TU PONES" : "YOU PUT",
    "NOSOTROS PONEMOS" : "WE PUT",
    "EL PONE" : "HE PUTS",
    "ELLA PONE" : "SHE PUTS",
    "ESO PONE" : "IT PUTS",
    "ELLOS PONEN" : "THEY PUT",
    "USTEDES PONEN" : "YOU PUT",
    "YO SOY/ESTOY" : "I AM",
    "TU ERES/ESTAS" : "YOU ARE",
    "NOSOTROS SOMOS/ESTAMOS" : "WE ARE",
    "EL ES/ESTA" : "HE IS",
    "ELLA ES/ESTA" : "SHE IS",
    "ESO ES/ESTA" : "IT IS",
    "ELLOS SON/ESTAN" : "THEY ARE",
    "USTEDES SON/ESTAN" : "YOU ARE",
    "YO ENVIE" : "I SEND",
    "TU ENVIAS" : "YOU SEND",
    "NOSOTROS ENVIAMOS" : "WE SEND",
    "EL ENVIA" : "HE SENDS",
    "ELLA ENVIA" : "SHE SENDS",
    "ESO ENVIA" : "IT SENDS",
    "ELLOS ENVIAN" : "THEY SEND",
    "USTEDES ENVIAN" : "YOU SEND",
    "YO TENGO" : "I HAVE",
    "TU TIENES" : "YOU HAVE",
    "NOSOTROS TENEMOS" : "WE HAVE",
    "EL TIENE" : "HE HAS",
    "ELLA TIENE" : "SHE HAS",
    "ESO TIENE" : "IT HAS",
    "ELLOS TIENEN" : "THEY HAVE",
    "USTEDES TIENEN" : "YOU HAVE",  
}

tiempos_will = {
    "YO IRE" : "I WILL GO",
    "TU IRAS" : "YOU WILL GO",
    "NOSOTROS IREMOS" : "WE WILL GO",
    "EL IRA" : "HE WILL GOES",
    "ELLA IRA" : "SHE WILL GOE",
    "ESO IRA" : "IT WILL GOE",
    "ELLOS IRAN" : "THEY WILL GO",
    "USTEDES IRAN" : "YOU WILL GO",
    "YO VENDRE" : "I WILL COME",
    "TU VENDRAS" : "YOU WILL COME",
    "NOSOTROS VENDREMOS" : "WE WILL COME",
    "EL VENDRA" : "HE WILL COME",
    "ELLA VENDRA" : "SHE WILL COME",
    "ESO VENDRA" : "IT WILL COME",
    "ELLOS VENDRAN" : "THEY WILL COME",
    "USTEDES VENDRAN" : "YOU WILL COME",
    "YO DARE" : "I WILL GIVE",
    "TU DARAS" : "YOU WILL GIVE",
    "NOSOTROS DAREMOS" : "WE WILL GIVE",
    "EL DARA" : "HE WILL GIVE",
    "ELLA DARA" : "SHE WILL GIVE",
    "ESO DARA" : "IT WILL GIVE",
    "ELLOS DRAN" : "THEY WILL GIVE",
    "USTEDES DARAN" : "YOU WILL GIVE",
    "YO TOMARE" : "I WILL TAKE",
    "TU TOMARAS" : "YOU WILL TAKE",
    "NOSOTROS TOMAREMOS" : "WE WILL TAKE",
    "EL TOMARA" : "HE WILL TAKE",
    "ELLA TOMARA" : "SHE WILL TAKE",
    "ESO TOMARA" : "IT WILL TAKE",
    "ELLOS TOMARAN" : "THEY WILL TAKE",
    "USTEDES TOMARAN" : "YOU WILL TAKE",
    "YO MANTENDRE" : "I WILL KEEP",
    "TU MANTENDRA" : "YOU WILL KEEP",
    "NOSOTROS MANTENDREMOS" : "WE WILL KEEP",
    "EL MANTENDRA" : "HE WILL KEEP",
    "ELLA MANTENDRA" : "SHE WILL KEEP",
    "ESO MANTENDRA" : "IT WILL KEEP",
    "ELLOS MANTENDRAN" : "THEY WILL KEEP",
    "USTEDES MANTENDRAN" : "YOU WILL KEEP",
    "YO DEJARE" : "I WILL LET",
    "TU DEJARAS" : "YOU WILL LET",
    "NOSOTROS DEJAREMOS" : "WE WILL LET",
    "EL DEJARA" : "HE WILL LET",
    "ELLA DEJARA" : "SHE WILL LET",
    "ESO DEJARA" : "IT WILL LET",
    "ELLOS DEJARAN" : "THEY WILL LET",
    "USTEDES DEJARAN" : "YOU WILL LET",
    "YO VERE" : "I WILL SEE",
    "TU VERAS" : "YOU WILL SEE",
    "NOSOTROS VEREMOS" : "WE WILL SEE",
    "EL VERA" : "HE WILL SEE",
    "ELLA VERA" : "SHE WILL SEE",
    "ESO VERA" : "IT WILL SEE",
    "ELLOS VERAN" : "THEY WILL SEE",
    "USTEDES VERAN" : "YOU WILL SEE",
    "YO PAREZCERE" : "I WILL SEEM",
    "TU PARECERAS" : "YOU WILL SEEM",
    "NOSOTROS PARECEREMOS" : "WE WILL SEEM",
    "EL PARECERA" : "HE WILL SEEM",
    "ELLA PARECERA" : "SHE WILL SEEM",
    "ESO PARECERA" : "IT WILL SEEM",
    "ELLOS PARECERAN" : "THEY WILL SEEM",
    "USTEDES PARECERAN" : "YOU WILL SEEM",
    "YO CONSEGUIRE" : "I WILL GET",
    "TU CONSEGUIRAS" : "YOU WILL GET",
    "NOSOTROS CONSEGUIREMOS" : "WE WILL GET",
    "EL CONSIGUIRA" : "HE WILL GET",
    "ELLA CONSIGUIRA" : "SHE WILL GET",
    "ESO CONSIGUIRA" : "IT WILL GET",
    "ELLOS CONSIGUIRAN" : "THEY WILL GET",
    "USTEDES CONSIGUIRAN" : "YOU WILL GET",
    "YO HARE/ACCION" : "I WILL DO",
    "TU HARAS/ACCION" : "YOU WILL DO",
    "NOSOTROS HAREMOS/ACCION" : "WE WILL DO",
    "EL HARA/ACCION" : "HE WILL DO",
    "ELLA HARA/ACCION" : "SHE WILL DO",
    "ESO HARA/ACCION" : "IT WILL DO",
    "ELLOS HARAN/ACCION" : "THEY WILL DO",
    "USTEDES HARAN/ACCION" : "YOU WILL DO",
    "YO HARE/CREAR" : "I WILL MAKE",
    "TU HARAS/CREAR" : "YOU WILL MAKE",
    "NOSOTROS HAREMOS/CREAR" : "WE WILL MAKE",
    "EL HARA/CREAR" : "HE WILL MAKE",
    "ELLA HARA/CREAR" : "SHE WILL MAKE",
    "ESO HARA/CREAR" : "IT WILL MAKE",
    "ELLOS HARAN/CREAR" : "THEY WILL MAKE",
    "USTEDES HARAN/CREAR" : "YOU WILL MAKE",
    "YO PONDRE" : "I WILL PUT",
    "TU PONDRAS" : "YOU WILL PUT",
    "NOSOTROS PONDREMOS" : "WE WILL PUT",
    "EL PONDRA" : "HE WILL PUT",
    "ELLA PONDRA" : "SHE WILL PUT",
    "ESO PONDRA" : "IT WILL PUT",
    "ELLOS PONDRAN" : "THEY WILL PUT",
    "USTEDES PONDRAN" : "YOU WILL PUT",
    "YO SERE/ESTARE" : "I WILL AM",
    "TU SERAS/ESTARAS" : "YOU WILL ARE",
    "NOSOTROS SEREMOS/ESTAREMOS" : "WE WILL ARE",
    "EL SERA/ESTARA" : "HE WILL BE",
    "ELLA SERA/ESTARA" : "SHE WILL BE",
    "ESO SERA/ESTARA" : "IT WILL BE",
    "ELLOS SERAN/ESTARAN" : "THEY WILL ARE",
    "USTEDES SORAN/ESTARAN" : "YOU WILL ARE",
    "YO ENVIARE" : "I WILL SEND",
    "TU ENVIARAS" : "YOU WILL SEND",
    "NOSOTROS ENVIAREMOS" : "WE WILL SEND",
    "EL ENVIARA" : "HE WILL SEND",
    "ELLA ENVIARA" : "SHE WILL SEND",
    "ESO ENVIARA" : "IT WILL SEND",
    "ELLOS ENVIRAN" : "THEY WILL SEND",
    "USTEDES ENVIRAN" : "YOU WILL SEND",
    "YO TENDRE" : "I WILL HAVE",
    "TU TENDRAS" : "YOU WILL HAVE",
    "NOSOTROS TENDREMOS" : "WE WILL HAVE",
    "EL TENDRA" : "HE WILL HAVE",
    "ELLA TENDRA" : "SHE WILL HAVE",
    "ESO TENDRA" : "IT WILL HAVE",
    "ELLOS TENDRAN" : "THEY WILL HAVE",
    "USTEDES TENDRAN" : "YOU WILL HAVE",
    "YO IRIA" : "I WOULD GO",
    "TU IRIAS" : "YOU WOULD GO",
    "NOSOTROS IRIAMOS" : "WE WOULD GO",
    "EL IRIA" : "HE WOULD GOES",
    "ELLA IRIA" : "SHE WOULD GOE",
    "ESO IRIA" : "IT WOULD GOE",
    "ELLOS IRIAN" : "THEY WOULD GO",
    "USTEDES IRIAN" : "YOU WOULD GO",
    "YO VENDRIA" : "I WOULD COME",
    "TU VENDRIAS" : "YOU WOULD COME",
    "NOSOTROS VENDRIAMOS" : "WE WOULD COME",
    "EL VENDRIA" : "HE WOULD COME",
    "ELLA VENDRIA" : "SHE WOULD COME",
    "ESO VENDRIA" : "IT WOULD COME",
    "ELLOS VENDRIAN" : "THEY WOULD COME",
    "USTEDES VENDRIAN" : "YOU WOULD COME",
    "YO DARIA" : "I WOULD GIVE",
    "TU DARIAS" : "YOU WOULD GIVE",
    "NOSOTROS DARIAMOS" : "WE WOULD GIVE",
    "EL DARIA" : "HE WOULD GIVE",
    "ELLA DARIA" : "SHE WOULD GIVE",
    "ESO DARIA" : "IT WOULD GIVE",
    "ELLOS DARIAN" : "THEY WOULD GIVE",
    "USTEDES DARIAN" : "YOU WOULD GIVE",
    "YO TOMARIA" : "I WOULD TAKE",
    "TU TOMARIAS" : "YOU WOULD TAKE",
    "NOSOTROS TOMARIAMOS" : "WE WOULD TAKE",
    "EL TOMARIA" : "HE WOULD TAKE",
    "ELLA TOMARIA" : "SHE WOULD TAKE",
    "ESO TOMARIA" : "IT WOULD TAKE",
    "ELLOS TOMARIAN" : "THEY WOULD TAKE",
    "USTEDES TOMARIAN" : "YOU WOULD TAKE",
    "YO MANTENDRIA" : "I WOULD KEEP",
    "TU MANTENDRIA" : "YOU WOULD KEEP",
    "NOSOTROS MANTENDIAMOS" : "WE WOULD KEEP",
    "EL MANTENDRIA" : "HE WOULD KEEP",
    "ELLA MANTENDRIA" : "SHE WOULD KEEP",
    "ESO MANTENDRIA" : "IT WOULD KEEP",
    "ELLOS MANTENDRIAN" : "THEY WOULD KEEP",
    "USTEDES MANTENDRIAN" : "YOU WOULD KEEP",
    "YO DEJARIA" : "I WOULD LET",
    "TU DEJARIAS" : "YOU WOULD LET",
    "NOSOTROS DEJARIAMOS" : "WE WOULD LET",
    "EL DEJARIA" : "HE WOULD LET",
    "ELLA DEJARIA" : "SHE WOULD LET",
    "ESO DEJARIA" : "IT WOULD LET",
    "ELLOS DEJARIAN" : "THEY WOULD LET",
    "USTEDES DEJARIAN" : "YOU WOULD LET",
    "YO VERIA" : "I WOULD SEE",
    "TU VERIAN" : "YOU WOULD SEE",
    "NOSOTROS VERIAMOS" : "WE WOULD SEE",
    "EL VERIA" : "HE WOULD SEE",
    "ELLA VERIA" : "SHE WOULD SEE",
    "ESO VERIA" : "IT WOULD SEE",
    "ELLOS VERIA" : "THEY WOULD SEE",
    "USTEDES VERIAN" : "YOU WOULD SEE",
    "YO PAREZCERIA" : "I WOULD SEEM",
    "TU PARECERIA" : "YOU WOULD SEEM",
    "NOSOTROS PARECERIAMOS" : "WE WOULD SEEM",
    "EL PARECERIA" : "HE WOULD SEEM",
    "ELLA PARECERIA" : "SHE WOULD SEEM",
    "ESO PARECERIA" : "IT WOULD SEEM",
    "ELLOS PARECERIAN" : "THEY WOULD SEEM",
    "USTEDES PARECERIAN" : "YOU WOULD SEEM",
    "YO CONSEGUIRIA" : "I WOULD GET",
    "TU CONSEGUIRIAS" : "YOU WOULD GET",
    "NOSOTROS CONSEGUIRIAMOS" : "WE WOULD GET",
    "EL CONSIGUIRIA" : "HE WOULD GET",
    "ELLA CONSIGUIRIA" : "SHE WOULD GET",
    "ESO CONSIGUIRIA" : "IT WOULD GET",
    "ELLOS CONSIGUIRIAN" : "THEY WOULD GET",
    "USTEDES CONSIGUIRIAN" : "YOU WOULD GET",
    "YO HARIA/ACCION" : "I WOULD DO",
    "TU HARIAS/ACCION" : "YOU WOULD DO",
    "NOSOTROS HARIAMOS/ACCION" : "WE WOULD DO",
    "EL HARIA/ACCION" : "HE WOULD DO",
    "ELLA HARIA/ACCION" : "SHE WOULD DO",
    "ESO HARIA/ACCION" : "IT WOULD DO",
    "ELLOS HARIAN/ACCION" : "THEY WOULD DO",
    "USTEDES HARIAN/ACCION" : "YOU WOULD DO",
    "YO HARIA/CREAR" : "I WOULD MAKE",
    "TU HARIAS/CREAR" : "YOU WOULD MAKE",
    "NOSOTROS HARIAMOS/CREAR" : "WE WOULD MAKE",
    "EL HARIA/CREAR" : "HE WOULD MAKE",
    "ELLA HARIA/CREAR" : "SHE WOULD MAKE",
    "ESO HARIA/CREAR" : "IT WOULD MAKE",
    "ELLOS HARIAN/CREAR" : "THEY WOULD MAKE",
    "USTEDES HARIAN/CREAR" : "YOU WOULD MAKE",
    "YO PONDRIA" : "I WOULD PUT",
    "TU PONDRIAS" : "YOU WOULD PUT",
    "NOSOTROS PONDRIAMOS" : "WE WOULD PUT",
    "EL PONDRIA" : "HE WOULD PUT",
    "ELLA PONDRIA" : "SHE WOULD PUT",
    "ESO PONDRIA" : "IT WOULD PUT",
    "ELLOS PONDRIAN" : "THEY WOULD PUT",
    "USTEDES PONDRIAN" : "YOU WOULD PUT",
    "YO SERIA/ESTARIA" : "I WOULD AM",
    "TU SERIAS/ESTARIAS" : "YOU WOULD ARE",
    "NOSOTROS SERIAMOS/ESTARIAMOS" : "WE WOULD ARE",
    "EL SERIA/ESTARIA" : "HE WOULD BE",
    "ELLA SERIA/ESTARIA" : "SHE WOULD BE",
    "ESO SERIA/ESTARIA" : "IT WOULD BE",
    "ELLOS SERIAN/ESTARIAN" : "THEY WOULD ARE",
    "USTEDES SERIAN/ESTARIAN" : "YOU WOULD ARE",
    "YO ENVIARIA" : "I WOULD SEND",
    "TU ENVIARIAS" : "YOU WOULD SEND",
    "NOSOTROS ENVIARIAMOS" : "WE WOULD SEND",
    "EL ENVIARIA" : "HE WOULD SEND",
    "ELLA ENVIARIA" : "SHE WOULD SEND",
    "ESO ENVIARIA" : "IT WOULD SEND",
    "ELLOS ENVIARIAN" : "THEY WOULD SEND",
    "USTEDES ENVIARIAN" : "YOU WOULD SEND",
    "YO TENDRIA" : "I WOULD HAVE",
    "TU TENDRIAS" : "YOU WOULD HAVE",
    "NOSOTROS TENDRIAMOS" : "WE WOULD HAVE",
    "EL TENDRIA" : "HE WOULD HAVE",
    "ELLA TENDRIA" : "SHE WOULD HAVE",
    "ESO TENDRIA" : "IT WOULD HAVE",
    "ELLOS TENDRIAN" : "THEY WOULD HAVE",
    "USTEDES TENDRIAN" : "YOU WOULD HAVE", 
}
palabras_1 = {
    "LUZ" : "LIGHT",
    "TRABAJO" :"WORK",
    "ACEITE" :"OIL",
    "OFERTA" :"OFFER",
    "OSCURO" :"DARK",
    "PLANTA" : "PLANT",
    "SONRISA" :"SMILE",
    "CHOQUE" :"SMASH",
    "FLOR" :"FLOWER",
    "FIN" : "END",
    "SOMBRERO" : "HAT",
    "HERMANO" :"BROTHER",
    "AZUL" : "BLUE",
    "EUROPA": "EUROPE",
    "JARDIN" : "GARDEN",
    "AQUI" : "HERE",
    "TENEDOR" : "FORK",
    "ATRASADO" : "LATE",
    "MIS, MI, MIO" : "MY",
    "HERMANA" : "SISTER",
    "HIJO" : "SON",
    "CIELO" : "SKY",
    "ESTO, ESTAS" : "THIS",
    "AMARILLO" : "YELLOW",
    "OPUESTO" : "OPPOSITE",
    "GUAPO" : "HANDSOME",
    "BONITA" : "PRETTY",
    "HERMOSO" : "BEAUTIFUL",
    "FEO" : "UGLY",
    "DIA" : "DAY",
    "HOY": "TODAY",
    "MAÑANA" : "TOMORROW",
    "AYER" : "YESTERDAY",
    "SEMANA" : "WEEK",
    "AÑO" : "YEAR",
    "CAMINAR/PASEO" : "WALK",
    "ATAQUE" : "ATTACK",
    "PINTURA" : "PAINT",
    "LLORAR" : "CRY",
    "MANZANA" : "APPLE",
    "MALO/MALA/MAL" : "BAD",
    "NIÑO" : "BOY",
    "NIÑA" : "GIRL",
    "NEGRO" : "BLACK",
    "AMARGO" : "BITTER",
    "LIMPIO" : "CLEAN",
    "PROFUNDO" : "DEEP",
    "SUCIO" : "DIRTY",
    "BEBIDA" : "DRINK",
    "VESTIDO" : "DRESS",
    "CASA" : "HOUSE",
    "BODADOSO/AMABLE" : "KIND",
    "HOMBRE" : "MAN",
    "MUJER" : "WOMAN",
    "NUEVO" : "NEW",
    "NOTICIA" : "NEWS",
    "POBRE" : "POOR",
    "PLATO" : "PLATE",
    "RIO" : "RIVER",
    "FUERTE" : "STRONG",
    "DEBIL" : "WEAK",
    "PEQUEÑO" : "SMALL",
    "DULCE" : "SWEET",
    "MESA" : "TABLE",
    "AGUA" : "WATER",
    "JOVEN" : "YOUNG",
    "VIEJO" : "OLD",
    "SABIA" : "WISE",
    "BLANCO" : "WHITE"
}
palabras_2 = {
    "ALUMBRADO" : "LIGHTING",
    "TRABAJANDO" : "WORKING",
    "ACEITANDO" : "OILING",
    "OFRECIENDO" : "OFFERING",
    "OBSCURECIENDO" : "DARKING",
    "PLANTANDO" : "PLANTING",
    "SONRIENDO" : "SMILING",
    "CHOCANDO" : "SMASHING",
    "FLORECIENDO" : "FLOWERING",
    "FINALIZADO" : "ENDING",
    "TRABAJO" : "WORK",
    "EMPLEO" : "JOB",
    "ESTE, ESTA, ESTO" : "THIS",
    "ESE, ESA, ESO" : "THAT",
    "MUY" : "VERY",
    "BUEN, BUENO, BUENA" : "GOOD",
    "CIMA, CUMBRE" : "TOP",
    "ARBOL" : "TREE",
    "BEBE, NENE" : "BABY",
    "MONTAÑA" : "MOUNTAIN",
    "LAPIZ" : "PENSIL",
    "VERDE" : "GREEN",
    "MAPA" : "MAP",
    "Y" : "AND",
    "ENFERMO/MALESTAR" : "SICK",
    "ENFERMO/ENFERMEDAD FISICA O MENTAL" : "ILL",
    "CAMINO" : "ROAD",
    "PLAY" : "JUEGO",
    "PLAYING" : "JUGANDO"
}

examen_1 = {
    "OFFER" : "OFERTA",
    "MONDAY" : "LUNES",
    "MI HERMANA ESTA EN URUGUAY" : "MY SISTER IS IN URUGUAY",
    "ESA ES UNA BUENA IDEA" : "THAT IS A GOOD IDEA",
    "EMPLEO" : "JOB",
    "BLUE" : "AZUL",
    "TU ESTAS RETRASADO" : "YOU ARE LATE",
    "SON" : "HIJO",
    "ELLOS ESTAN PLANTANDO UN ARBOL" : "THEY ARE PLANTING A TREE",
    "BAD" : "MALO",
    "MUY" : "VERY",
    "MY HERMANA ESTA EN EL JARDIN" : "MY SISTER IS IN THE GARDEN",
    "MAN" : "HOMBRE",
    "EL ES UN HOMBRE AMABLE" : "HE IS A KIND MAN",
    "CASA" : "HOUSE",
    "ESTE ES EL CAMINO A CASA" : "THIS IS THE ROAD TO HOME",
    "PLATE": "PLATO",
    "BOY" : "CHICO",
    "EL LAPIZ ES AZUL" : "THE PENCIL IS BLUE",
    "PLANTAR" : "PLANT",
    "AGUA" : "WATER",
    "HERE" : "AQUI",
    "ELLAS SON MIS HERMANAS" : "THEY ARE MY SISTERS",
    "IDEA" : "IDEA",
    "VIOLIN" : "VIOLIN",
    "FLOR" : "FLOWER",
    "HE" : "EL",
    "MIO, MI" : "MY",
    "EL CIELO ES AZUL" : "THE SKY IS BLUE",
    "PAINT" : "PINTURA",
    "YOUNG" : "JOVEN",
    "GARDEN" : "JARDIN",
    "LIGHT" : "LUZ",
    "ELLOS" : "THEY",
    "NOSOTROS VAMOS A CASA" : "WE GO TO HOME ",
    "VESTIDO" : "DRESS",
    "PINTANDO" : "PAINTING",
    "BASE" : "BASE",
    "ESO ES BUENO" : "IT IS GOOD",
    "APPLE" : "MANZANA",
    "CLEAN" : "LIMPIO",
    "WALKING" : "CAMINANDO",
    "EL ESTA PINTANDO" : "HE IS PAINTING",
    "FORK" : "TENEDOR",
    "NEWS" : "NOTICIA",
    "RIVER" : "RIO",
    "SKY" : "CIELO",
    "MI HIJO ESTA AQUI" : "MY SON IS HERE",
    "ELLA ESTA SONRIENDO" :  "SHE IS SMILING",
    "HOY" : "TODAY",
    "NIÑA" : "GIRL",
    "NEGRO" : "BLACK",
    "AMARGO" : "BITTER",
    "LIMPIO" : "CLEAN",
    "ELLOS ESTAN EN EL RIO" : "THEY ARE IN THE RIVER",
    "PROFUNDO" : "DEEP",
    "SUCIO" : "DIRTY",
    "BEBIDA" : "DRINK",
    "VESTIDO" : "DRESS",
    "AMARILLO" : "YELLOW",
    "EL ES MI HERMANO" : "HE IS MY BROTHER",
}

past_verb = {
    "FUI": "WENT",
    "VINE": "CAME",
    "TOME": "TOOK",
    "DI": "GAVE",
    "MANTUVE": "KEPT",
    "DEJE": "LET",
    "VI": "SAW",
    "DIJE": "SAID",
    "PARECI": "SEEMED",
    "CONSEGUI": "GOT",
    "HICE-ACCION": "DID",
    "HICE-CREAR": "MADE",
    "PUSE": "PUT",
    "ERA-ESTABA": "WAS",
    "ENVIE": "SENT",
    "TUVE": "HAD",
    "ERAN-ESTABAN" : "WERE"
}

def pracitca_dict(data):
    aciertos = 0
    fallos = 0
    print('''
          veras a continuacion una serie de palabras en español, tu tarea es escribirlos al ingles.
          (en caso de que quieras salir de la practica escribe EXIT)
          ''')
    while True:
        print(".....................................................")
        print(f"*aciertos* : {aciertos}, *fallos* : {fallos}")
        verb_random = choice(list(data.keys()))
        respuesta = input(f"traduce al ingles *  '{verb_random}' * >>> ").upper()
        if respuesta == "EXIT" :
            break
        elif data[verb_random] == respuesta:
            print ("                 *correcto*                ")
            aciertos += 1
        else :
            print(f"    *incorrecto*       la respuesta era {data[verb_random]}" )
            fallos +=1


def repaso (datos):
    aciertos = 0
    fallos = 0
    print('''
          veras a continuacion una serie de palabras en español, tu tarea es escribirlos al ingles.
          (en caso de que quieras salir de la practica escribe EXIT)
          ''')
    
    for i in datos:
        print("********************************************")
        print(f"*aciertos* : {aciertos}, *fallos* : {fallos}")
        prueba = input(f"traduce: {i} >> ").upper()
        if prueba == "EXIT" :
            break
        elif prueba == datos[i]:
            print ("      *** CORRECTO ***")
            aciertos += 1
        else:
            while True:
                fallos += 1
                print (f" INCORRECTO la esrespuesta es {datos[i]} ")
                print(f"*aciertos* : {aciertos}, *fallos* : {fallos}")
                prueba = input(f"traduce: {i} >> ").upper()
                if prueba == "EXIT" :
                    break
                elif prueba == datos[i]:
                    print ("      *** CORRECTO ***")
                    break
def deseo(dato):
    while True:
                eleccion = int(input('''
                                    Que te gustaria?:
                                    presiona:
                                    1) Aprender
                                    2) Practicar
                                    '''))
                if eleccion == 1:
                    repaso(dato)
                elif eleccion == 2:
                    pracitca_dict(dato)
                else:
                    print("Eleccion incorrecta.")

def start():
    while True:
        print("bienvenido a : practicas de ingles")
        print('''
            1) verbos importantes
            2) pronombres
            3) pronombres + verbos 
            4) tiempos futuro will,would, may, migth
            5) palabras 1
            6) palabras 2
            7) *** examen 1 ***
            8) verbos importantes en pasado
            ''')
        elije = int(input("presiona el numero correspondiente a la opcion que desees >>> "))

        if elije == 1 :
            deseo(dict_verb)
        elif elije == 2 : 
            deseo(dict_pronombres)
        elif elije == 3 :
            deseo(frase_pronombre_and_verbs)
        elif elije == 4:
            deseo(tiempos_will)
        elif elije == 5 :
            deseo(palabras_1)
        elif elije == 6:
            deseo(palabras_2)
        elif elije == 7:
            repaso(examen_1)
        elif elije == 8 :
            deseo(past_verb)
        else:
            print ("eleccion incorrecta")


if __name__ == "__main__":
    start()